# Generated by Django 3.0.3 on 2023-09-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('Licence_no', models.CharField(max_length=15)),
                ('insurance', models.CharField(max_length=100)),
                ('vechile_no', models.IntegerField()),
                ('rc_book_no', models.CharField(max_length=100)),
                ('aadhar_no', models.IntegerField()),
                ('phone_no1', models.IntegerField()),
                ('phone_no2', models.IntegerField()),
                ('carImage', models.ImageField(upload_to='images/carImage/')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/hotel/')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('bussiness_registration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='lodge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('typeOfroom', models.CharField(max_length=100)),
                ('total_rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('place_desc', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('pimage', models.ImageField(upload_to='images/places/')),
            ],
        ),
    ]
