# Generated by Django 3.0.3 on 2023-09-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='aadhar_no',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cab',
            name='phone_no1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cab',
            name='phone_no2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cab',
            name='vechile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='bussiness_registration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lodge',
            name='total_rooms',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
