# Generated by Django 3.0.3 on 2023-09-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0002_auto_20230922_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
