# Generated by Django 3.0.3 on 2023-09-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0003_hotels_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='carImage',
            field=models.ImageField(null=True, upload_to='carImage/'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='image',
            field=models.ImageField(null=True, upload_to='hotel/'),
        ),
        migrations.AlterField(
            model_name='places',
            name='pimage',
            field=models.ImageField(null=True, upload_to='places/'),
        ),
    ]
