# Generated by Django 3.0.3 on 2023-09-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0005_auto_20230922_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='rating',
            field=models.CharField(max_length=100),
        ),
    ]
