# Generated by Django 3.0.3 on 2023-09-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0007_auto_20230922_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
