# Generated by Django 4.0 on 2024-03-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exp', '0009_auto_20230922_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cab',
            old_name='Licence_no',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='cab',
            old_name='driver_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='carImage',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='phone_no1',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='phone_no2',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='rc_book_no',
        ),
        migrations.RemoveField(
            model_name='cab',
            name='vechile_no',
        ),
    ]
